### ISSUE TITLE
malicious purposes

### ISSUE THREAD

**Issue by yoursunny** [is-a-dev/maintainer-docs#1]
[pr-review.md](https://github.com/is-a-dev/maintainer-docs/blob/d56cf14ec4d90d335e11b304a7cee914bb00e2de/pr-review.md#contents-of-the-website) contains the following:

> We need to make sure that the contents being hosted via the record being registered is used for malicious purposes.

This sentence, simplified, reads: we need to make sure that **the contents is used for malicious purposes**.

I guess this is not what you meant to say.

**Comment by TheBotlyNoob** [comment]
Thanks for reporting the issue! This has been fix [with this commit](https://github.com/is-a-dev/maintainer-docs/commit/a253aa078436e103049b3621950b029ac2c59266)!
